import { CommonModule } from '@angular/common';
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormsModule } from '@angular/forms';
import jsPDF from 'jspdf';
@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './reports.html',
  styleUrls: ['./reports.css']
})
export class Reports implements OnInit {
  reports: any[] = [];
  filteredReports: any[] = [];

  searchText = '';
  loading = false;
  errorMessage = '';

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.loadReports();
  }

  loadReports(): void {
    this.loading = true;

    const savedReports = JSON.parse(localStorage.getItem('mriReports') || '[]');

    this.reports = savedReports;
    this.filteredReports = [...this.reports];

    this.loading = false;

    console.log('LOCAL REPORTS:', this.filteredReports);

    this.cdr.detectChanges();
  }

  searchReports(): void {
    const text = this.searchText.toLowerCase().trim();

    if (!text) {
      this.filteredReports = [...this.reports];
      return;
    }

    this.filteredReports = this.reports.filter((report) =>
      report.patientName?.toLowerCase().includes(text) ||
      report.prediction?.toLowerCase().includes(text) ||
      report.tumorType?.toLowerCase().includes(text)
    );
  }

downloadReport(report: any): void {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text('Brain MRI Detection Report', 105, 19, {
    align: 'center',
  });

  doc.setTextColor(0, 0, 0);

  let y = 45;

  // Patient Information
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text('Patient Information', 20, y);

  y += 10;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  doc.text(`Patient Name : ${report.patientName || 'N/A'}`, 20, y);
  y += 8;

  doc.text(`Age          : ${report.age || 'N/A'}`, 20, y);
  y += 8;

  doc.text(`Gender       : ${report.gender || 'N/A'}`, 20, y);
  y += 18;

  // Prediction Result
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text('Prediction Result', 20, y);

  y += 10;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  doc.text(`Prediction   : ${report.prediction || 'N/A'}`, 20, y);
  y += 8;

  doc.text(`Tumor Type   : ${report.tumorType || 'N/A'}`, 20, y);
  y += 8;

  doc.text(`Confidence   : ${report.confidence || 0}%`, 20, y);
  y += 18;

  // Report Details
  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);
  doc.text('Report Details', 20, y);

  y += 10;

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);

  doc.text(`Image Name   : ${report.imageName || 'N/A'}`, 20, y);
  y += 8;

  doc.text(
    `Generated On : ${
      report.createdAt ? new Date(report.createdAt).toLocaleString() : 'N/A'
    }`,
    20,
    y
  );

  y += 20;

  // MRI image at the end
 // MRI Scan
// ================= MRI IMAGE PAGE =================

if (report.imagePreview) {

  doc.addPage();

  doc.setFontSize(18);
  doc.setTextColor(37, 99, 235);
  doc.text("Uploaded MRI Scan", 105, 20, { align: "center" });

  // Maximum image size
  const maxWidth = 90;
  const maxHeight = 90;

  // Create an image element to get actual dimensions
  const img = new Image();

  img.onload = () => {

    const ratio = Math.min(
      maxWidth / img.width,
      maxHeight / img.height
    );

    const width = img.width * ratio;
    const height = img.height * ratio;

    // Center the image
    const x = (210 - width) / 2;
    const y = 40;

    // Border
    doc.roundedRect(x - 5, y - 5, width + 10, height + 10, 3, 3);

    doc.addImage(
      report.imagePreview,
      "JPEG",
      x,
      y,
      width,
      height
    );

    doc.setFontSize(11);
    doc.setTextColor(120);

    doc.text(
      "Uploaded Brain MRI Image",
      105,
      y + height + 15,
      { align: "center" }
    );

    doc.save(`${report.patientName}_Report.pdf`);
  };

  img.src = report.imagePreview;

  return;
}

// Save if there is no image
doc.save(`${report.patientName}_Report.pdf`);
  // Footer
  if (y > 270) {
    doc.addPage();
    y = 30;
  }

  doc.setDrawColor(37, 99, 235);
  doc.line(20, y, 190, y);

  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);

  doc.text(
    'This report was generated by the Brain MRI Tumor Detection System.',
    105,
    y,
    { align: 'center' }
  );

  doc.save(`${report.patientName || 'MRI'}_Report.pdf`);
}
}